### ISSUE TITLE
Root Cause Analysis: undefined is not an object

### ISSUE THREAD

**Issue by steebe** [lshadler/indecision-plaza#31]
**Overview**
The application is recently stalling out upon clicking the "Pick a Restaurant" button. It appears to be a defect related to the issue card loading before the Yelp API results have been returned (thus causing a business entity to be created with a null JSON object). 

**Complete When**
1. A document outlining the actual root cause of this defect has been created in the wiki. Proof helps!

**Comment by sumwatshade** [comment]
I believe this is due to a portion of the `food-finder.service` that references the API. the internals of the API response should return the object, and was likely being beat in a race condition with a return statement outside of the response that was not contained within `if-else` logic.
